name: Test build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@67c2d834b83f6a05dd0d398d20d21b79f062d7fa # v5.2.2
