name: Run test commands

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-check:
    uses: fizyk/actions-reuse/.github/workflows/shared-pr-check.yml@c76d10cf9448b3a9afdbef29e727e0fd00b2f544 # v5.2.8
    with:
      dependency-manager: 'uv'
