name: Run test commands

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-check:
    uses: fizyk/actions-reuse/.github/workflows/shared-pr-check.yml@a77b9a9554742fe1ad70b0c0cd589235fd0a60fb # v5.2.1
    with:
      dependency-manager: 'uv'
