name: Run linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  pre-commit:
    uses: fizyk/actions-reuse/.github/workflows/shared-pre-commit.yml@67c2d834b83f6a05dd0d398d20d21b79f062d7fa # v5.2.2
