name: Run pytest tests

on:
  workflow_call:
    inputs:
      python-versions:
        description: 'Supported python versions'
        default: '["3.10", "3.11", "3.12", "3.13", "3.14", "3.15", "pypy-3.11"]'
        required: false
        type: string
      mongo:
        description: 'MongoDB version'
        required: true
        type: number
      os:
        description: 'Operating system to run tests on'
        default: 'ubuntu-latest'
        required: false
        type: string
    secrets:
      codecov_token:
        description: 'Codecov token'
        required: false

jobs:
  tests:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
    env:
      OS: ${{ inputs.os }}
      PYTHON: ${{ matrix.python-version }}
      MONGODB: ${{ inputs.mongo }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install MongoDB
      uses: ankane/setup-mongodb@a01a9a4888b0b7bb1813656d8653fb2b06ae50d8 # v1
      with:
        mongodb-version: ${{ inputs.mongo }}
    - name: Run test
      id: run_serial_tests
      uses: fizyk/actions-reuse/.github/actions/uv@7eefbd6ffc6c6787ad3be6ce93dcf475e3ae99b5 # v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
        command: python -m coverage run -m pytest -p no:xdist
        env: '{"COVERAGE_PROCESS_START": ".coveragerc", "COVERAGE_FILE": ".coverage.serial"}'
    - name: Combine and export serial coverage
      if: ${{ always() && (steps.run_serial_tests.conclusion == 'success' || steps.run_serial_tests.conclusion == 'failure') }}
      uses: fizyk/actions-reuse/.github/actions/coverage-combine-export-uv@d10cfa3ac0d2a53b405a7a1dcada20eb40a34f08 # v5.2.3
      with:
        data-file: .coverage.serial
        output-file: coverage.xml
    - name: Run xdist test
      id: run_xdist_tests
      uses: fizyk/actions-reuse/.github/actions/uv-run@42b61e053c1d70a61deb42b323c1a2229e2e7fe0 # v5.5.0
      with:
        command: python -m coverage run -m pytest -n auto --dist loadgroup --max-worker-restart=0
        env: '{"COVERAGE_PROCESS_START": ".coveragerc", "COVERAGE_FILE": ".coverage.xdist"}'
    - name: Combine and export xdist coverage
      if: ${{ always() && (steps.run_xdist_tests.conclusion == 'success' || steps.run_xdist_tests.conclusion == 'failure') }}
      uses: fizyk/actions-reuse/.github/actions/coverage-combine-export-uv@d10cfa3ac0d2a53b405a7a1dcada20eb40a34f08 # v5.2.3
      with:
        data-file: .coverage.xdist
        output-file: coverage-xdist.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{ secrets.codecov_token }}
        flags: linux
        env_vars: OS,PYTHON,MONGODB
        files: ./coverage.xml,./coverage-xdist.xml
        fail_ci_if_error: false
